apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: asia.gcr.io/stephen-f52d1/cs-api
    context: api-python
  - image: asia.gcr.io/stephen-f52d1/cs-ip
    context: image-proccessing
deploy:
  kubectl:
    manifests:
    - k8s/api.yaml
    - k8s/ip.yaml
