apiVersion: v1
kind: Service
metadata:
  name: cam-scanner-api-service
spec:
  selector:
    name: cam-scanner-api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cam-scanner-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: cam-scanner-api
  template:
    metadata:
      labels:
        app: cam-scanner
        name: cam-scanner-api
    spec:
      containers:
        - name: cam-scanner-api
          image: asia.gcr.io/stephen-f52d1/cs-api
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
