# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ImageProcessRequest_pb2 as ImageProcessRequest__pb2


class ImageProcessingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ScanningDocument = channel.unary_unary(
        '/ImageProcessing/ScanningDocument',
        request_serializer=ImageProcessRequest__pb2.Image.SerializeToString,
        response_deserializer=ImageProcessRequest__pb2.Image.FromString,
        )


class ImageProcessingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ScanningDocument(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ScanningDocument': grpc.unary_unary_rpc_method_handler(
          servicer.ScanningDocument,
          request_deserializer=ImageProcessRequest__pb2.Image.FromString,
          response_serializer=ImageProcessRequest__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageProcessing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
